### PR TITLE
Allow using the dynamically created module easier from code

### PR DESCRIPTION
**Pull request by jezdez**
It bothered me that the dynamically created module would have this odd unrolled name in it and wanted to also allow importing the setting class instance from real code.

E.g. currently runserver shows

```
Django version 1.4, using settings 'acme.settings_Production_unrolledcbsettings'
```

But it shouldn't be hard to guess the path of the class based setting. That's why this patch would instead prints

```
Django version 1.4, using settings 'acme.settings.production'
```

Code in Django that uses `import_module` to load the `SETTINGS_MODULE` will continue working, as it will use `acme.settings.production` as a module path and user code can use the import system on their own by importing the settings object directly with `from acme.settings import production`.

What do you think?

### CODE REVIEW

**Comment by matthewwithanm** [comment]
Thanks, @jezdez! I'm definitely not opposed to changing the "unrolled" module name, and I like the proxy idea, but I do have a few misgivings about some of these changes. I'll list them out and you can let me know your thoughts:

<div>
1. In the current code, the user can choose where to "unroll" the settings if they don't like the default by defining a <code>SETTINGS_MODULE</code> setting. For example:
</div>


<pre><code>class Production(DjangoDefaults):
    SETTINGS_MODULE = 'myproject.settings.production'
</code></pre>


That's not to say that we shouldn't have a better default, but I'd rather not get rid of this feature because, no matter how good our default is, the user might disagree.

<p>
2. I thought it might be a good idea to have the "unrolled" settings module be on the same level as the original module. If you create a module <code>a.b.c.settings</code>, which gets unrolled to <code>a.b.c.settings.production</code>, you might get surprising results from any code that looks at the module containing <code>settings.SETTINGS_MODULE</code>. In practice, I'm not sure how often this would be an issue, but it seemed to me that there wasn't any real benefit to further nesting the module, so the small benefit of keeping them siblings won out.
</p>


<p>
3. It doesn't seem out of the question that somebody would have a setup like this:
</p>


<pre><code>myproject/
    settings/
        __init__.py    # Imports switcher and registers some settings classes
        dev.py         # Defines settings classes used for development
        production.py  # Same as above, but for production
</code></pre>


In this case, if a settings class named `Dev` or `Production` were defined, I think we'd wind up with a collision since the factory module (`myproject.settings`) already contains `dev` and `production` modules. On the other hand, going with a suffix pretty much eliminates this risk. I chose "_unrolledcbsettings" so that somebody debugging would imediately be clued in to where this module came from, and why no corresponding file exists in the filesystem. (In addition, though this is a very very small nitpick, I had avoiding using `__class__` to form the name because I had in in the back of my head that you could really use anything from which you could extract attributes—e.g. a module. This would still work with your code, but the "unrolled" module name would be "myproject.settings.module".)

So those were my reasons for the unweildy name: maintaining siblingship with the original factory module, preventing collisions, and being clear about the module's origin. However, I do agree that it's pretty…hideous.

Let me know what you think.

**Comment by jezdez** [comment]
1. Good point, I've updated my fork to allow overriding the module in which the unrolling happens again.
2. But that's the beauty of my changes, importing the value of `settings.SETTINGS_MODULE` _is_ possible in that case (`import a.b.c.settings.production`) as I'm setting a module level object with that name. When I tried the app yesterday it was actually what I stumbled over, as I wasn't able to work with the unrolled settings how they are done right now.
3. Well, first of all, it wouldn't be a module, but a object that we'd create the collision with. So a class called `myproject.settings.dev.Dev` should in my opinion create a `SETTINGS_MODULE` of `myproject.settings.dev.dev` to prevent this kind of bleeding effect. I understand why you chose to suffix the name of the auto generated object but I think we wouldn't even have to make the user think about where a setting came from, as it's literally was just the class that auto populates an object with the same name (lowered of course) in the same module as the class. This is of course just a shortcut to a whole different strategy of just making the user call `dev = Dev()` at the end of the module.

**Comment by matthewwithanm** [comment]
> But that's the beauty of my changes, importing the value of settings.SETTINGS_MODULE is possible in that case (import a.b.c.settings.production) as I'm setting a module level object with that name.

Ah, yeah. The inability to import is definitely a bug. I'll come back to that, but first…

What I was trying to describe in 2 above was this: if any code attempts to find the module the _contains_ the settings module, it will get unexpected results (compared to what seems intuitive based on the value you passed to `configure()`). In other words:

```
'a.b.c.settings'.rsplit('.', 1)[0] != 'a.b.c.settings.production'.rsplit('.', 1)[0]
```

whereas

```
'a.b.c.settings'.rsplit('.', 1)[0] == 'a.b.c.settings_production'.rsplit('.', 1)[0]
```

Like I said, I'm not sure how often (if ever) this would be an issue. But since I couldn't think of a benefit to using 'a.b.c.settings.production' at the time anyway, I figured the best approach was to keep things as similar as possible.

Now, back to the import bug…

Yeah, that was definitely an oversight. However, wouldn't it be better to address it in the [module-creation loop](https://github.com/matthewwithanm/django-classbasedsettings/blob/b27c0e643797d2c4ea455307ac896a3d3c9219eb/cbsettings/__init__.py#L40-48)? With your last commit, we're creating modules recursively but not really finishing the job: only the last one gets added as an attribute of its parent. This may be better:

```
# Create the settings module.
parts = settings_dict['SETTINGS_MODULE'].split('.')

all_modules = map(lambda x: '.'.join(x), [parts[0:i + 1] for i in range(len(parts))])
module = None
for i, module_name in enumerate(all_modules):
    try:
        module = import_module(module_name)
    except ImportError:
        parent_module = module
        module = imp.new_module(module_name)
        sys.modules[module_name] = module
        if parent_module:
            setattr(parent_module, module_name, module)

# Unroll the settings into a new module.
for k, v in settings_dict.items():
    setattr(module, k, v)

os.environ[DJANGO_SETTINGS_MODULE] = settings_dict['SETTINGS_MODULE']
```

Conversely, if we don't really want to create modules recursively (for example, to eliminate the accidental creation of modules by typo), we should probably provide a helpful error. But personally, I'm leaning toward allowing the recursive creation of modules.

> Well, first of all, it wouldn't be a module, but a object that we'd create the collision with. So a class called myproject.settings.dev.Dev should in my opinion create a SETTINGS_MODULE of myproject.settings.dev.dev to prevent this kind of bleeding effect.

I think you're making the assumption that `myproject.settings.dev.Dev` is being used as the factory (i.e. that's the path passed to `configure()`), however, that's not necessarily the case. You can pass any callable that returns a settings instance—indeed, that's what the `switcher` utility is. Consider the following setup:

```
myproject/
    settings/
        __init__.py
        dev.py
```

with

```
# settings/__init__.py
from cbsettings import switcher
from .dev import Dev
switcher.register(Dev)  # No conditions so Dev is always used.
```

and

```
cbsettings.configure('myproject.settings.switcher')
```

With [the commit before last](https://github.com/jezdez/django-classbasedsettings/blob/a45b22bac72ad1c253c563629534c94eb45ebc6b/cbsettings/__init__.py#L41), the default value for `SETTINGS_MODULE` would be `'myproject.settings.dev'` (overriding the module defined by dev.py). With [the most recent commit](https://github.com/jezdez/django-classbasedsettings/blob/7e9b0c17cfdda573123642c72da20b0de97f14d4/cbsettings/__init__.py#L41), it would be `'myproject.settings.switcher'` (overriding the switcher instance in __init__.py). With [the code in v1.0b2](https://github.com/matthewwithanm/django-classbasedsettings/blob/9f3a1328eadd8ff365233ae99d360f14efd47de8/cbsettings/__init__.py#L37), it would be `'myproject.settings_switcher_unrolledcbsettings'`—admittedly not very pretty, but at least free of conflict. Again, I'm very open to changing this default to something less ugly (at the very least, it should be lower'd), but obviously we need to try to minimize the risk of collision.

Thanks again for your interest. This discussion has been great!

**Comment by jezdez** [comment]
Thanks for your feedback, I really appreciate that and have thought about it. You're right, having the suffix attached to the created module _is_ the better way as it simply doesn't involve any kind of advanced magic just to make it "nicer". I've enjoyed thinking about the problem though, as it shows how antiquated Django's module based settings system really is. I'm closing this pull request for now, as I don't see a need to work on it further.

**Pull request closed without merging**
